### ISSUE TITLE
promote.js has error on IE8

### ISSUE THREAD

**Issue by iahu** [CreateJS/PreloadJS#109]
promote method has error on IE8. The value `supP` will be `undefined`.

code at [line](https://github.com/CreateJS/PreloadJS/blob/master/src/createjs/utils/promote.js#L80):
```js
var subP = subclass.prototype, supP = (Object.getPrototypeOf&&Object.getPrototypeOf(subP))||subP.__proto__;
```

**Comment by lannymcnie** [comment]
Thanks. We are looking into this now.

**Comment by lannymcnie** [comment]
PreloadJS will no longer support IE8, as of version 0.6.0. For IE8 support, please use version 0.4.1. 
Related: https://github.com/CreateJS/PreloadJS/issues/112
