### ISSUE TITLE
preloadjs not working in IE8 — Error

### ISSUE THREAD

**Issue by JonathanDoelan** [CreateJS/PreloadJS#112]
IE8 throws "Object doesn't support this property or method".
Debugger outlines: function a(a,b,c){this.AbstractLoader_constructor(),this.init(a,b,c)}
I'm using preloadjs without any other createjs-libs. Only for IMG-Preloading.

EDIT: After intensive testing … it doesn't work on Chrome < 19, Opera < 12, IE < 9, Safari 6 (but it does work on Safari 5.1 on Windows)

**Comment by lannymcnie** [comment]
Thanks for the report. The new inheritance method does have some issues in older browsers, and we are looking at solutions.

In the mean time, the previous version (0.4.0) should work fine.

**Comment by JonathanDoelan** [comment]
ok thx. that worked for me.

**Comment by lannymcnie** [comment]
This is not going to be fixed. The new inheritance model is incompatible with IE8 and earlier. Please use PreloadJS 0.4.1 if you require IE8 support. Cheers.
