### ISSUE TITLE
WebAudioLoader has no _handleError function, causes TypeError

### ISSUE THREAD

**Issue by Evaugh** [CreateJS/PreloadJS#113]
In `createjs-2014.12.12.combined.js`

    Uncaught TypeError: Cannot read property 'apply' of undefined (11:37:12:591 | error, javascript)
        at (anonymous function) (https://code.createjs.com/createjs-2014.12.12.combined.js:20727:17)

In the `_sendComplete` function of the `Loader` prototype, a proxy is created using `this._handleError` (line 23742), which doesn't exist. Error occurs when the proxy function is executed.

**Comment by lannymcnie** [comment]
I believe this was already resolved in SoundJS in GitHub -- it might be a while before we get a new version of the combined libs up. 

Thanks for the report!

**Comment by liuyi** [comment]
It looks have not be fixed.

**Comment by OJayRobinson** [comment]
SoundJS has fixed this issue, replacing the incorrect _handleError with expected _sendError.
The fix is available in SoundJS-NEXT, which requires PreloadJS-NEXT to function correctly.

Hope that helps

**Comment by lannymcnie** [comment]
New versions were live on the CDN in May 2015, so this should be solved. I am closing it - but please feel free to re-open if you can still reproduce.

**Comment by boardgames** [comment]
Hi! reproduced this error...
When cleared Cookie and Cache - preloader.min is throw this error.
