### ISSUE TITLE
queue.cancel() throws many javascript errors

### ISSUE THREAD

**Issue by ottonascarella** [CreateJS/PreloadJS#116]
Hi guys,

Thanks for this amazing piece of software.

I found a thing that might insterest you guys.

http://codepen.io/ottonascarella/pen/myMwoR

On the example above, I create a delay call to cancel the queue loading after 5s its started.
As a consequence, you see loads of JavaScript errors coming up due to the cancel.

PS: it'd be good to have a non minified version of the software available on cdn so we can actually try and help pursuing the error ourselves without having to clone the code.

**Comment by lannymcnie** [comment]
You can get a non-minified version in GitHub, or link to the combined library on the CDN:
http://code.createjs.com/createjs-2014.12.12.combined.js

Thanks for the report, we will check it out

**Comment by ottonascarella** [comment]
Cool.
Updated the pen to use the full createjs unminified.
