### ISSUE TITLE
Using the same preloaded spritesheet multiple times at the same time

### ISSUE THREAD

**Issue by catalinberta** [CreateJS/PreloadJS#118]
I am using SpriteStage to make some spritesheet animations, but running the same preloaded spritesheet in multiple canvases at the same time isn't working, it only works for the first canvas, the rest are black. It works if I create a preloadjs object for each animation/canvas, but I wouldn't like to create a preloaded object for every spritesheet, as I have many + many canvases, thus, I would end up with tons of preloaded objects.

Here is a <a href="http://jsfiddle.net/L8af7w1L/5/">Fiddle</a>

**Comment by wdamien** [comment]
When using SpriteStage you need to use unique images for them to display correctly. Calling .cloneNode() on each image before using them works.  Here is an updated version on your Fiddle;

```javascript
var queue = new createjs.LoadQueue();
queue.on("complete", handleLoad, this);
queue.loadManifest([{
    id: "people1",
    src: "http://i296.photobucket.com/albums/mm182/CodeH4x0r/explosion17.png"
}], true);

var imageData, canvas_1, canvas_2, canvas_3, canvas_4, canvas_5, canvas6

    function handleLoad(evt) {

        for (var i = 1; i <= 5; i++) {
            var imageData = {
                images: [queue.getResult("people1").cloneNode()],
                frames: {
                    width: 64,
                    height: 64
                },
                framerate: 25,
                animations: {
                    run: [0, 25, true]
                }
            }

            canvas_1 = new SpriteAnim('canvas_' + i);
            canvas_1.start(imageData, 64, 64, false);

        }

    }
```

**Comment by catalinberta** [comment]
Thanks for the help, I will check soon.
