### ISSUE TITLE
External JSON manifests do not work

### ISSUE THREAD

**Issue by thellers** [CreateJS/PreloadJS#120]
Hi,

I'm trying to preload a bunch of MP3's that are listed in an external JSON manifest. I set up the JSON file and used it with queue.loadManifest, but it does not work. Only the JSON file is loaded, and not the MP3's indicated in the JSON manifest. If I set up the array of MP3's manually, or if I load and parse the JSON myself with JQuery, then pass the result to the LoadQueue, it works fine in both cases. This leads me to believe that the JSON loading in PreloadJS is at fault.

My JSON:
```javascript
[	
	{"src":"sounds/pop2.mp3", "id":"startDrag"},
	{"src":"sounds/ping.mp3", "id":"goodDrop"},
	{"src":"sounds/clang.mp3", "id":"badDrop"},
	
	{"src":"sounds/excellent.mp3", "id":"right1"},
	{"src":"sounds/superb.mp3", "id":"right2"},
	{"src":"sounds/thatsright.mp3", "id":"right3"},
	{"src":"sounds/fantastic.mp3", "id":"right4"},
	{"src":"sounds/brilliant.mp3", "id":"right5"},
	
	{"src":"sounds/ohdear.mp3", "id":"wrong1"},
	{"src":"sounds/trythatagain.mp3", "id":"wrong2"},
	{"src":"sounds/thatsnotquiteright.mp3", "id":"wrong3"},
	
	{"src":"sounds/welldone-activitycomplete-2.mp3", "id":"win"}
]
```

My Javascript:
```javascript
window.sounds = [	
	{src:"sounds/pop2.mp3", id:"startDrag"},
	{src:"sounds/ping.mp3", id:"goodDrop"},
	{src:"sounds/clang.mp3", id:"badDrop"},
	
	{src:"sounds/excellent.mp3", id:"right1"},
	{src:"sounds/superb.mp3", id:"right2"},
	{src:"sounds/thatsright.mp3", id:"right3"},
	{src:"sounds/fantastic.mp3", id:"right4"},
	{src:"sounds/brilliant.mp3", id:"right5"},
	
	{src:"sounds/ohdear.mp3", id:"wrong1"},
	{src:"sounds/trythatagain.mp3", id:"wrong2"},
	{src:"sounds/thatsnotquiteright.mp3", id:"wrong3"},
	
	{src:"sounds/welldone-activitycomplete-2.mp3", id:"win"}
]


function preload(app_id)
	{
		var q = window.q = new createjs.LoadQueue();
		q.installPlugin(createjs.Sound);
		
		var sound_manifest = app_id + "_sounds.json";
		console.log("Loading from " + sound_manifest);
		
		//Handling JSON myself with JQuery works fine
		$.getJSON(sound_manifest, function (data){
			if (data){
				q.loadManifest(data);
			}
		});
	
		
		//q.loadManifest({src:sound_manifest, type:"manifest"}); <--- THIS DOES NOT WORK!
		//q.loadManifest(window.sounds); <<--- THIS WORKS!
		q.on("complete", handleComplete, this);	
	}
```

**Comment by abritinthebay** [comment]
I'm seeing this as well.

In my case it's that the json files actually throw an error (causing complete to fire) but in fact they load fine - the files in the manifest are then parsed and loaded in the background fine.

However it causes the progress to fail and the callback to fire prematurely.

**Comment by lannymcnie** [comment]
We will look into this.

In the mean time, it doesn't look like your JSON manifest is the right format. You need to have more than just an array of files, since manifests also support additional properties like a `path`, the required format is:

```javascript
{
    manifest: [
        {"id":"image", "src":"path/to/file.jpg"}
    ]
}
```

PreloadJS requires the `manifest` property, which defines the array of files. Without it, it assumes it is just a normal JSON.

The issue @abritinthebay reported seems a little different. Can you post the error you are seeing?

**Comment by abritinthebay** [comment]
Similar issue - malformed JSON. So partially an error on my end.

The core issue though was the behavior after the error. The error caused the progress to be 100% and for the complete to fire. This is clearly the exact opposite of the situation (where it's not complete at all). Oddly it seemed that even tho the json was...  wrong it would load the files up to the syntax error (in my case a missing comma).

So while the *cause* was my sloppy comma checking (and being too tired to see that)... the resulting behavior still seems less than ideal.

If you'd like to see the final result it actually went live today: http://thelab.bleacherreport.com/jordan/

**Comment by lannymcnie** [comment]
If the manifest can't be parsed, or appears to have no files in it, then it would cause the queue to skip all the other files, since it is not aware of them. The queue is considered "complete", even though its contents failed to load.

**Comment by lannymcnie** [comment]
@abritinthebay Awesome site!

**Comment by abritinthebay** [comment]
Thank you! Took a lot of work :)

Interesting. To me that seems counter intuitive (as an error is thrown in the initial parsing of the manifest).
I get that one *file* error shouldn't tank a whole parsing of a list but it seems like if a manifest errors then the whole process is never complete... I mean, semantically.

I get the programatic reasons for doing it that way though.

Side note - if you look at the code (core.js) I'm loading a whole array of manifests. It would be *really* nice to have a feature for this in the code as the current work around (basically triggering from the complete function) is a bit... hacky.

Use case is for LARGE sites (like that) where you just want to preload a portion (or section) and then start the app while letting the rest do their work.

Anyhow, should be a separate feature request :)

**Comment by lannymcnie** [comment]
Yeah, all I am saying is that if the Preload queue never receives the files (due to the manifest not loading), then from its perspective, it has completed. It might be a little unintuitive to receive a `complete` event from the manifest if it encounters errors, however things like `stopOnError` and handling `error` events can help with that.

**Comment by gskinner** [comment]
@abritinthebay apologies if I'm misunderstanding the request, but you can nest manifests. You just need to specify a type of "manifest" (otherwise it is treated as JSON by default).

**Comment by abritinthebay** [comment]
Oh! well that is good to know. Maybe I just fail at reading the documentation. Didn't see that option.

**Comment by thellers** [comment]
Thanks,

Is there some place where the required structure of the manifest JSON is documented? I thought I had RTFM thoroughly but apparently missed this.

Cheers,

Andy

**Comment by lannymcnie** [comment]
No, you are right, this is not documented well. There are a bunch of sample JSON files in the GitHub repository, but we will make sure to beef up the documentation asap.

Thanks!

**Comment by thellers** [comment]
OK, thanks.

So, what other properties go in the manifest JSON? Anything I need to know
about?

{
    "foo":"bar", "foo2":"bar2", "foo3":"bar3", manifest[-- array of file
objects here--]
}

**Comment by lannymcnie** [comment]
Manifest loading supports a "manifest" property for the file list, as well as a "path" property, which is appended to the LoadQueue `basePath`, or just prepended to file paths when the file is loaded.

Essentially what happens is that the JSON is loaded, and then passed directly to a `LoadQueue.loadManifest()` call as the `manifest` parameter. This only happens if a "manifest" property is found on the JSON object, which is why an array of files will not work.

**Comment by thellers** [comment]
Great. Thanks!

**Comment by lannymcnie** [comment]
Pushed up documentation update to GitHub. The site might get an update soon as well.
