### ISSUE TITLE
IE will issue multiple HTTP requests for audio based on the data attribute

### ISSUE THREAD

**Issue by christopherliu** [CreateJS/PreloadJS#125]
If an audio file is loaded by PreloadJS, Internet Explorer will make multiple network requests for it based on the data attribute. Thus, if my manifest has data=10, IE will download the same file 10 times.

I'm using this code:
```javascript
        var loadQueue = new createjs.LoadQueue();
        // Firefox and Opera will load "music.ogg"
        // Browsers with MP3 support will load "music.mp3"
        createjs.Sound.alternateExtensions = ["mp3"];
        loadQueue.installPlugin(createjs.Sound);
        createjs.Sound.registerPlugins([createjs.HTMLAudioPlugin]);

        var manifest = [{
            "id" : "music",
            "src" : "/music.ogg",
            'data' : 20
        }];
        loadQueue.loadManifest(manifest);
```

The number of requests made is actually 2x-1, where x is the data attribute. I have pasted a screenshot from Internet Explorer's developer tools:

![ie](https://cloud.githubusercontent.com/assets/519376/6309271/8de138ae-b919-11e4-9273-f24b6a8ac60f.PNG)

This behavior can also be observed on the CreateJS demo page [here](http://www.createjs.com/Demos/PreloadJS/MediaGrid) by using the Live Edit function and changing the data attribute. Interestingly, on that page the number of requests is x, not 2x-1.

See also: http://community.createjs.com/discussions/soundjs/175-sounds-loading-twice-in-ie-and-hangs-some-time-in-ie9

**Comment by OJayRobinson** [comment]
This is expected behavior with the HTMLAudioPlugin, as Chrome previously required each audio tag to be precreated and loaded.  Generally browser caching will let you load the additional tags with minimal impact.  This will happen with SoundJS internal loading and PreloadJS loading.

Testing the latest behaviour of Chrome is something we're hoping to make time for, and hopefully we'll be able to remove this unfortunate restraint.

Hope the helps.

**Comment by christopherliu** [comment]
It does a bit, thanks @OJayRobinson. While caching should minimize the impact, it seems that there is still some request overhead - in particular, say you're loading a file that takes 10 seconds to load; IE appears to initialize all of the network requests simultaneously, even if only one copy is needed.

Additionally, I'm using the preloader on a separate page from the actual data, so preloading is not directly tied to playback. It would still be preferable to use the same manifests in each case, but doing so results in 10 audio tags on the preloading page even when they won't be used.

It sounds like these are browser specific restrictions. Could the code check for IE vs. Chrome and only require multiple tags in the latter case? I've had to patch data=1 in all my preloading code for the moment.

**Comment by OJayRobinson** [comment]
That's not a bad idea, when I get to looking into it if the chrome restriction still exists I will consider it as an alternative.  Thanks.

**Comment by christopherliu** [comment]
Thanks! One other possibility: Is there any reason loadManifest can't patch data=1 itself? I'm guessing this is because it's tied to playback for other usage scenarios, but I haven't tested it.

**Comment by OJayRobinson** [comment]
The data parameter is used to tell SoundJS how many copies of a specific audio clip can be played at once, with defaults if it is not specified.  We would not want the library to change it on the user, as that would defeat it's purpose.  

The HTMLAudioPlugin has a [defaultNumChannels](http://www.createjs.com/Docs/SoundJS/classes/HTMLAudioPlugin.html#property_defaultNumChannels) property that can be modified like this:
`createjs.HTMLAudioPlugin.defaultNumChannels = 1;`

If you set that before loading, any files that do not have a data property will default to 1 when HTMLAudioPlugin is active.  Note that WebAudioPlugin and FlashAudioPlugin both default to 100, as there is no cost associated with allowing more.

**Comment by OJayRobinson** [comment]
I've logged a related feature request [here](https://github.com/CreateJS/SoundJS/issues/152).

**Comment by OJayRobinson** [comment]
A change for this has been pushed to [SoundJS-NEXT](https://github.com/CreateJS/SoundJS), and would probably benefit from some real world testing if you have time.
