### ISSUE TITLE
Nested manifests more than one level deep do not surface their items

### ISSUE THREAD

**Issue by Pajamaman** [CreateJS/PreloadJS#126]
Let's say I'm loading an external manifest file like so:

    function init() {
        loader.loadManifest('manifest.json');
    }

My manifest file is defined as:

    {
        "manifest": [
            {"src": "robot.json", "type": "manifest"}
        ]
    }

The sub-manifest:

    {
        "path": "assets/"
        "manifest": [
            {"id": "img_robot", "src": "img/robot.png"}
        ]
    }

When I call `loader.getItems()`, I get something like the following result:

    [
        "item": {
            "id": "manifest.json",
            "type": "manifest"
        }
        "rawResult": [manifest as string]
        "result": {
            "manifest": [
                {
                    "id": "robot.json",
                    "type": "manifest"
                }
            ]
        }
    ]

I would expect to find img_robot somewhere in this object, but as far as I can tell it is not. Do I have to explicitly load all sub-manifests in order to access their resources?

**Comment by lannymcnie** [comment]
Sub-manifest should properly surface the items. Your `getItems` response doesn't look right. We will look into it.

Thanks!

**Comment by lannymcnie** [comment]
I was able to reproduce this, and have determined the issue:

LoadQueue's surface their "loaded items" via the `_loadQueueBackup` array, which is essentially an unmodified list of files that were requested. This works one-level deep. In your example, the ManifestLoader that loads "robot.json" will contain the "robot.png", but when asked for its items, only serves the items that it requested (the json file) to the top level LoadQueue.

We should be able to solve this shortly.

**Comment by lannymcnie** [comment]
I just pushed a fix for this. Please test if you are able to, we are likely putting together another dot-release shortly.

Thanks!
