### ISSUE TITLE
createjs.LoadQueue observes loadTimeout for loading sound files when WebAudioPlugin is first; does not when HTMLAudioPlugin is first

### ISSUE THREAD

**Issue by christopherliu** [CreateJS/PreloadJS#127]
I recently switched to using WebAudioPlugin as the first plugin for SoundJS. I noticed that now, when I set createjs.LoadQueue.loadTimeout, PreloadJS would respect it and stop immediately (firing a LoadQueue.complete event!) after the loadTimeout was encountered. (See [also](http://community.createjs.com/discussions/preloadjs/965-trying-to-diagnose-random-users-cant-load-sound-files#comment_31584521))

However, I never noticed this problem before because HTMLAudioPlugin used to be first, and it would consistently wait past the loadTimeout to load files. (I was using PreloadJS 0.4.1 and SoundJS 0.5.2, in case this has changed.)

I don't personally have any strong preferences on which method to use, but the inconsistency was causing bugs. Thank you!

**Comment by OJayRobinson** [comment]
This has changed, PreloadJS currently uses [createjs.LoadItem.loadTimeout](http://www.createjs.com/Docs/PreloadJS/classes/LoadItem.html#property_loadTimeout) which is set to [LoadQueue.LOAD_TIMEOUT](http://www.createjs.com/Docs/PreloadJS/classes/LoadQueue.html#property_LOAD_TIMEOUT)  in 0.6.0 and LoadItem.LOAD_TIMEOUT_DEFAULT in NEXT.  SoundJS respects this value and also uses them when loading internally without PreloadJS.

Worth noting from the loadTimeout doc "This only applies to tag-based and and XHR (level one) loading, as XHR (level 2) provides its own timeout event."

WebAudioLoader relies on XHR and will use level 2 where its available, which seems to be [everywhere](http://caniuse.com/#feat=xhr2).

Hope that helps.

**Comment by lannymcnie** [comment]
Closing this out, since @OJayRobinson indicated it has changed. If the issue still exists with the latest version, please feel free to reopen.
