### ISSUE TITLE
add .path property to createjs.LoadItem

### ISSUE THREAD

**Issue by OJayRobinson** [CreateJS/PreloadJS#128]
LoadQueue._createLoadItem is setting a path property on a LoadItem (line 1365), but LoadItem does not include a path property in its definition.

I suggest we add it.

**Comment by lannymcnie** [comment]
I believe this is an auto-generated value that is cleared before the load is complete. I don't know if it makes sense to doc it.

**Comment by OJayRobinson** [comment]
I'm not sure if it is cleared, but it is used by other classes which is why I would recommend it be doc'd
