### ISSUE TITLE
External Spritesheet json files do not preload the image data

### ISSUE THREAD

**Issue by hayesmaker** [CreateJS/PreloadJS#129]
Is it expected behaviour, that if a spritesheet.json (exported from Texturepacker) is queued to load from a 
LoadQueue, then the json is loaded first, then the image is loaded outside of my LoadQueue, so the LoadQueue "complete" event is fired when the json is loaded, not when both the json and the image data have loaded?

Sometimes my app loads before the image data, and I don't see the animations play until I refresh from the cache a few times.

Should I tell the preload to load my spritesheet image explicitly as well as it's json data file?

Below is my preload queue code:

    this.assetsLoader = new createjs.LoadQueue(true);
    this.assetsLoader.on("error", this.handleAssetsError, this);
    this.assetsLoader.on("progress", this.handleAssetsProgress, this);
    this.assetsLoader.on("complete", this.handleAssetsLoaded, this);
    this.assetsLoader.loadManifest(this.game.setup.spritesManifest);

here is my spritesheetsManifest:

    "spritesManifest" : [
        {"src": "assets/sprites/bigwin_1.json", "id": "bigWinAnim"},
        {"src": "assets/sprites/static-images.json", "id": "staticImages"},
        {"src": "assets/sprites/symbol_anims.json", "id": "symbolAnims"}
      ],

here is an example spritesheet.json:
    {
	"images": [
		"assets/sprites/static-images.png"
	],
	"frames": [
		[
			1,
			217,
			116,
			103
		],
		[
			848,
			109,
			116,
			103
		],
		[
			727,
			109,
			116,
			103
                //...etc

**Comment by lannymcnie** [comment]
The idea of the SpriteSheet loader is that it loads the JSON, then internally reads and loads the images, and then fires a complete event. It should complete only AFTER the images are ready for use. Check out the SpriteSheetLoader sample in the GitHub. 

Do not add your images to the main queue, as it will load them again. With XHR loading, this might actually result in a second full load since it can not use the cache.

If you are seeing different results, can you isolate to a simple demo, and provide the source?

**Comment by hayesmaker** [comment]
Yes this is not the result we are seeing.  The complete event is fired before the network inspector shows the images have loaded.  Codepen: http://codepen.io/hayesmaker/pen/zxaNYX

**Comment by lannymcnie** [comment]
@hayesmaker Your codepen just shows you loading raw JSON, and making the spritesheet yourself. Set the type of the manifest item to "spritesheet", and it will preload the images for you, and return you a SpriteSheet object.

**Comment by gskinner** [comment]
To provide a concrete example of what @lannymcnie is saying, your manifest entry would look like this:
````
{src: "http://andy-hayes.com/web/kingkong/assets/sprites/symbol_anims.json", id:"symbolAnims", type:"spritesheet"}
````
http://codepen.io/anon/pen/OPBEwY

**Comment by hayesmaker** [comment]
thanks all :)
