### ISSUE TITLE
XHRRequest: some doubts

### ISSUE THREAD

**Issue by elderNosferatu** [CreateJS/PreloadJS#134]
Sorry for my English and my GoogleTranslate :).
I have some doubts about the piece of code:
427. ...
428. } else { // Old IE versions use a different approach
429. ..for (var i = 0, l = s.ACTIVEX_VERSIONS.length; i < l; i++) {
430. ....var axVersion /* Webstorm says: Unused local variable axVersion */ = s.ACTIVEX_VERSIONS[i];
431. ......try {
432. ........req = new ActiveXObject(axVersions /* Probably should be axVersion  */);
433. ........break;
434. ...

**Comment by lannymcnie** [comment]
Thanks! We will check it out.
