### ISSUE TITLE
Loading mp4 video with SoundJS installed fails

### ISSUE THREAD

**Issue by sebastiancarlsson** [CreateJS/PreloadJS#140]
I'm having an issue with the sound plugin for PreloadJS, using the [example in the docs](http://createjs.com/Docs/PreloadJS/modules/PreloadJS.html) as a base, adding an mp4 video file to the manifest creates a `Cannot read property 'apply' of undefined` error which I believe is the issue that is described here: https://github.com/CreateJS/PreloadJS/issues/113. I presume that the Sound plugin mistakenly identifies the video as an audio file. I thought that the solution would be to add a `type` property to the items in the manifest (i.e. `createjs.AbstractLoader.SOUND` and so forth) but this doesn't seem to do anything.

```
var queue = new createjs.LoadQueue();
queue.installPlugin(createjs.Sound);
queue.on("complete", handleComplete, this);
queue.loadFile({id:"sound", src:"http://path/to/sound.mp3", type: createjs.AbstractLoader.SOUND});
queue.loadManifest([
     {id: "myImage", src:"path/to/myImage.jpg", type: createjs.AbstractLoader.IMAGE},
     {id: "myVideo", src:"path/to/myVideo.mp4", type: createjs.AbstractLoader.VIDEO}
 ]);

function handleComplete() {
    createjs.Sound.play("sound");
    var image = queue.getResult("myImage");
    document.body.appendChild(image);
}
```

**Comment by lannymcnie** [comment]
Looks like SoundJS wants to handle MP4 files, but does not differentiate between VIDEO or SOUND. I recommend using a separate queue for the video, which does not have SoundJS installed as a plugin. You can easily set up the second queue as the `next` queue on the first one.

```javascript
queue1.next = queue2;
```

**Comment by lannymcnie** [comment]
Leaving this open to remind us to look for other solutions.

**Comment by lannymcnie** [comment]
This was solved recently in the NEXT build ((Dec 12)[https://github.com/CreateJS/SoundJS/commit/48515173811d87fd6ee5ed55f79c00705549901b]). As long as video items in the manifest have the type "video", SoundJS will ignore them.
