### ISSUE TITLE
Got error when load audio on Safari when amount of files is big. 

### ISSUE THREAD

**Issue by liuyi** [CreateJS/PreloadJS#143]
It works fine on other browsers, got error when load a list of audio files on safari.
fire this error, when all the sounds loaded.
But if the  amount of audio files it not too big, the error not appear.
preloadjs-0.6.0.combined.js 

```
[Error] TypeError: undefined is not an object (evaluating 'method.apply')
	(anonymous function) (preloadjs-NEXT.combined.js, line 237)
TypeError: undefined is not an object (evaluating 'method.apply')
```

code:

```js
        _self.ebookMod.loader.on("complete", _self._onfileCompleted);
        _self.ebookMod.loader.on("progress",_self._onfileLoading);
        _self.ebookMod.loader.loadManifest(files);
```

**Comment by OJayRobinson** [comment]
I believe this is already fixed in SoundJS-Next, which requires PreloadJS-Next.  You can grab both from github.

Hope that helps.

**Comment by lannymcnie** [comment]
New versions of Preload + Sound were pushed to the CDN in May, 2015 - so this should be solved. Feel free to re-open if the problem persists.
