### ISSUE TITLE
403 stops preloader w/o throwing error

### ISSUE THREAD

**Issue by eloyer** [CreateJS/PreloadJS#144]
Hi, I'm finding that my LoadQueue stops in its tracks when encountering a 403 error, and doesn't call the error handler. This is when using tag loading.

**Comment by OJayRobinson** [comment]
PreloadJS-Next includes a fix to TagLoader to properly handle errors.

**Comment by lannymcnie** [comment]
This should be available on the CDN. Please feel free to re-open if the problem persists.
