### ISSUE TITLE
loadManifest() : Tag loading instead of XHR

### ISSUE THREAD

**Issue by lbineau** [CreateJS/PreloadJS#145]
Hi,

I'm trying to load all the images of a manifest without XHR (tag loading method) but it doesn't work.
Is there any method to set the default protocol to all the files loaded ?

*Sample:*

```json
// manifest.json
{
    "path": "/medias/",
    "manifest": [
        {"src": "images/home-product.png", "id":"image-home"}
    ]
}
```
```javascript
var loader = new createjs.LoadQueue(false); // tag loading instead of XHR
section.loader.loadManifest(manifest.json);
loader.getResult(myElementId) // returns an IMG url="blob:..."
```
```javascript
var loader = new createjs.LoadQueue(false); // tag loading instead of XHR
section.loader.loadFile({"src": "/medias/images/home-product.png", "id":"image-home"});
loader.getResult(myElementId) // returns an IMG url="/medias/images/home-product.png"
```

**Comment by lbineau** [comment]
The problem appears when I'm trying to load an external JSON manifest file. With the JSON Javascript object, the method works fine.

**Comment by lannymcnie** [comment]
Sorry for the delayed response. JSON files should respect the `preferXHR` property. You must have a `callback` defined on the load item though, otherwise, it will just fail.

SpriteSheetLoader was recently fixed to work as well.
