### ISSUE TITLE
PreloadJS and LoadQueue file type deprecation in error

### ISSUE THREAD

**Issue by andruo11** [CreateJS/PreloadJS#146]
Hello -- looking at the docs for the LoadQueue class, under "File Types" it says:
http://createjs.com/docs/preloadjs/classes/LoadQueue.html

Supported types are defined on the AbstractLoader class, and include:
BINARY: Raw binary data via XHR
...Note: Loader types used to be defined on LoadQueue, but have been moved to AbstractLoader for better portability of loader classes, which can be used individually now. The properties on LoadQueue still exist, but are deprecated.

It says to use createjs.AbstractLoader when referencing file load types, instead of createjs.LoadQueue as it used to be. The LoadQueue way is now deprecated. But I could not get the raw results in an arraybuffer from my binary file preload *unless I used the createjs.LoadQueue syntax.

**Comment by andruo11** [comment]
I'm sorry, this happened because I was using an old version of the library!

**Comment by lannymcnie** [comment]
Awesome. LoadQueue's properties will be removed for the next release (0.7.0+)
