### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT  Error will kill preload when use TagRequest

### ISSUE THREAD

**Issue by wzhonggo** [CreateJS/PreloadJS#147]
```html
<html>
<head>
<title>demo</title>
<script src="jquery.min.js"></script>
<script src="preloadjs-0.6.0.combined.js"></script>
<script>
     var queue = new createjs.LoadQueue(false);

    $(document).ready(function () {
        var manifest = [];
         manifest.push({src: "https://www.google.com/images/nav_logo195.png", id: "google"});
         manifest.push({src: "https://tomcat.apache.org/images/tomcat.png", id: "tomcat"});

        queue.loadManifest(manifest,true);
		queue.on("complete", handleComplete);
		queue.on("error", handleError);
    });


    function handleComplete(event) {
        console.log("handleComplete");
        $(queue.getResult("google")).appendTo("body");
        $(queue.getResult("tomcat")).appendTo("body");
    }
    function handleError(event) {
        console.log("handleError");
    }
</script>
</head>
<body>
</body>
</html>
```

I  am in china and can not access google.com  without proxy. It will show **net::ERR_CONNECTION_TIMED_OUT**  in chrome console log  when perload https://www.google.com/images/nav_logo195.png without proxy and not call handleComplete method . I find it will call **TagRequest**   **_handleTimeout**  method  and dispatch **timeout** event   , but not call **handleError** method.

![google_logo_error](https://cloud.githubusercontent.com/assets/2763532/7956580/49062d2a-0a13-11e5-9ee6-fdac633499f0.png)

**Comment by wdamien** [comment]
@wzhonggo I can't reproduce this issue with the latest release; http://code.createjs.com/preloadjs-0.6.1.min.js Can you try 0.6.1? if it doesn't work feel free to re-open this issue.

**Comment by wzhonggo** [comment]
@wdamien It is till have this problem with http://code.createjs.com/preloadjs-0.6.1.min.js. You can‘t reproduce this issue maybe you still can access https://www.google.com/images/nav_logo195.png.
Whether there had been this error **net::ERR_CONNECTION_TIMED_OUT**  in chrome console when you test. I am in china and can not access google.com without proxy.

**Comment by wdamien** [comment]
@wzhonggo I was able to duplicate your issue using 0.6.0 with my own local proxy to block the image. But when I swap in the latest 0.6.1 release I cannot reproduce it. Are there any more details you can provide? Things like your exact browser version and OS version would be helpful.

**Comment by wzhonggo** [comment]
@wdamien Thanks for your quick response.  My OS version is **win7  64bit**, browser is  **chrome 43.0.2357.81** . I Override **TagRequest _handleTimeout** method and dispatch **error** event instead of **timeout** event.It still show  this error **net::ERR_CONNECTION_TIMED_OUT**, but will call 
**handleComplete** method and show [tomcat](https://tomcat.apache.org/images/tomcat.png) image in page.

```html
<!DOCTYPE html>
<html>
<head>
<title>[SmartBuidler_4_Lesson]</title>
<script src="jquery.min.js"></script>
<script src="http://code.createjs.com/preloadjs-0.6.1.min.js"></script>
<script>
      createjs.TagRequest.prototype._handleTimeout = function(){
            this._clean();
            this.dispatchEvent(new createjs.Event("error"));
       }

     var queue = new createjs.LoadQueue(false);


    $(document).ready(function () {
        var manifest = [];
         manifest.push({src: "https://www.google.com/images/nav_logo195.png", id: "google"});
         manifest.push({src: "https://tomcat.apache.org/images/tomcat.png", id: "tomcat"});

        queue.loadManifest(manifest,true);
		queue.on("complete", handleComplete);
		queue.on("error", handleError);
    });


    function handleComplete(event) {
        console.log("handleComplete");
        $(queue.getResult("google")).appendTo("body");
        $(queue.getResult("tomcat")).appendTo("body");
    }
    function handleError(event) {
        console.log("handleError");
    }
</script>
</head>
<body>
</body>
</html>
```
