### ISSUE TITLE
Preloading sound doesn't show progress

### ISSUE THREAD

**Issue by Manojraj** [CreateJS/PreloadJS#152]
Hey,

First of all, thanks for the plugin...  It is just amazing... I am using the NEXT version of both preloadjs and soundjs...

I am using preloadJS to preload audio. It works perfectly fine in iOS browsers(safari and chrome) showing the progress in percentage.

 But loading the same url in android chrome and other desktop browsers, the the progress is not happening but the audio is loaded... The progress is stuck at 0% and jump straight to 100% when the audio is fully loaded...

**Comment by Manojraj** [comment]
This is my code 

    var queue = new createjs.LoadQueue();
    createjs.Sound.alternateExtensions = ["mp3"];
    queue.installPlugin(createjs.Sound);
    queue.on("progress", onProgress);
    queue.on("complete", handleComplete);
    queue.loadFile({"id":uniqueSoundID, "src":soundPath});
    queue.loadManifest([{"id":"BlackBG", "src": "images/black_bg.jpg"},
     {"id":"newBG", "src": "images/newBG.jpg"}]);

**Comment by lannymcnie** [comment]
Some platforms and servers don't provide preload progress for all file types. If loading is _working_, but gives you no progress, then it's likely just not providing it. Progress is only available on XHR-based loading, and large-format HTML media like audio and video. PreloadJS does its best to listen for and expose progress events when they are available, but unfortunately they aren't always supported. 

Additionally, if you have multiple files, like your example above, then it could be taking no time for the second file, which would appear to not show progress. Do you have console logs showing the 0-100% symptom, or are you judging it from watching a progress bar or indicator? If there are multiple files, you should definitely see multiple progress events from the LoadQueue.

**Comment by lannymcnie** [comment]
Closing this, as it doesn't appear to be an issue. Feel free to re-open if the problem persists.

**Comment by loicparent** [comment]
_Hello,_

I encounter the same problem with a video.
In fact, the progress works correctly in my dev install (with MAMP) but when I go to the staging version of the site (on an external server), the progress jump directly from 0 to 100 (after the file is completely loaded).

Is there a server config that can solve this issue ?

_Thanks for your help and have a nice day._

**Comment by loicparent** [comment]
Ok thank you @lannymcnie, I will check this to server support.
