### ISSUE TITLE
Why doesn't work? Thx 

### ISSUE THREAD

**Issue by bingoqiu** [CreateJS/PreloadJS#154]
I use a manifest.json to preload assets. In the manifest file, there are musics, images, json-files(each is a string format spritesheet). Images and musics cam be used. But when I try to create a sprite using, it failed. Maybe it means I got a json-file but not a SpriteSheet by using loadqueue.getResult(id for jsonfile)?

**Comment by lannymcnie** [comment]
Is the JSON that is loaded specified as a "spritesheet" type? If not, it will just be JSON, and you will have to construct the SpriteSheet yourself. The SpriteSheetLoader is only used when you pass `type:"spritesheet"`, which will preload the images used in the definition (if possible), and construct a SpriteSheet instance for you.

**Comment by bingoqiu** [comment]
Thx very much. I have tried and still don't work.
In my js file:
```javascript
var loadQueue = new createjs.LoadQueue(true);
loadQueue.installPlugin(createjs.Sound);
loadQueue.loadManifest("assets/manifest.json");
var hero = new createjs.Sprite(loadQueue.getResult("hero"), "move");
```
In the manifest.json file:
```javascript
{
    "path": "assets/",
    "manifest": [
        {"id": "hero", "src": "hero.json", type":"createjs.AbstractLoader.SPRITESHEET"},
        {"id": "start", "src": "game_start.png"},
        {"id": "pause", "src": "game_pause.png"}
}
The hero.json file definition:
```javascript
{
    "images": ["assets/hero.png"],
    "frames": {
        "width": 99, "height": 123, "regX": 0, "regY": 0, "count": 2
    },
    "animations": {
        "move": {
            "frames": [0]
        },
        "shoot": {
            "frames": [1],
            "next": "move"
        }
    }
}
```
When I copy the content of hero.json to create a SpriteSheet and the hero Sprite, it works.

**Comment by bingoqiu** [comment]
:smile:Thanks very much!
