### ISSUE TITLE
How to use routing libraries like crossroads js with preload js?

### ISSUE THREAD

**Issue by farhoudz** [CreateJS/PreloadJS#159]
Hello guys,

I want to build a one page web site which has content that I want to load their assets when requested by the user, I want to use preload js which I have used before with the help of crossroads js to handle the routing, please advice.

Like this website in terms of functionality: http://www.thenerodesign.com

**Comment by lannymcnie** [comment]
PreloadJS allows you to request assets whenever you want, it is up to you when you load things, and will just be part of your application architecture. 

I recommend creating some simple tests to figure out how PreloadJS works, and reference the [documentation](http://createjs.com/docs/preloadjs/modules/PreloadJS.html) and [samples in GitHub](http://github.com/CreateJS/PreloadJS/). If you have some specific questions, I recommend you post them to [StackOverflow](http://stackoverflow.com), and if you encounter any bugs, please feel free to post them here.
