### ISSUE TITLE
SpriteSheetLoader does not respect preferXHR for images

### ISSUE THREAD

**Issue by esavichev** [CreateJS/PreloadJS#161]
### Problem
For some reasons (did not debug deeper) browsers on iPad (and possibly some other browsers) fail to load images with `preferXHR=true`. It's easy to set it to `false` when needed, but SpriteSheetLoader does not respect it.

### Description
SpriteSheetLoader loads JSON data via XHR (it is OK), and then creates a queue for images. That queue does not respect preferXHR parameter passed to LoadQueue.

AbstractLoader_constructor always receives `null` as preferXHR
`this.AbstractLoader_constructor(loadItem, null, createjs.AbstractLoader.SPRITESHEET);`

And images queue is being created with default value for preferXHR (which is `true`)
`var queue = this._manifestQueue = new createjs.LoadQueue();`

### Expected behavior
SpriteSheetLoader (and any other complex loader) should remember preferred loading method and try to instantiate any subqueues with this value if possible.

### Solution
```javascript
function SpriteSheetLoader(loadItem, preferXHR) {
	this.AbstractLoader_constructor(loadItem, preferXHR, createjs.AbstractLoader.SPRITESHEET);
	...
}

...

p._loadManifest = function (json) {
	if (json && json.images) {
		var queue = this._manifestQueue = new createjs.LoadQueue(this._preferXHR);
		...
		queue.loadManifest(json.images);
	}
}
```
Pretty easy and should not break anything, right? Hope to see this fix in next release.

**Comment by lannymcnie** [comment]
Good catch. Note that we are looking at removing the "sub-queues" in loaders such as SpriteSheetLoader, ManifestLoader, etc in favour of adding items back into the main queue instead, so things like preferXHR and maxConnections are properly handled.

Cheers.

**Comment by esavichev** [comment]
Actually adding items back into the main queue is even better as it gives more solid control on load progress. Anyway "sub-queue" items (until they exist) have to respect parent queue settings as much as it is possible.

**Comment by lannymcnie** [comment]
Agreed.

I have pushed preliminary support for the SpriteSheetLoader sub-queue to respect the basePath, preferXHR, and crossOrigin flags on the SpriteSheetLoader load item. The changes are in the NEXT version of PreloadJS in GitHub. 

Please let me know if you encounter any issues. Thanks for the report!
