### ISSUE TITLE
XMLHttpRequest error when making a file for clients to play locally?

### ISSUE THREAD

**Issue by jacksmack101** [CreateJS/PreloadJS#166]
I'm trying to figure out how to get a flash HTML5 presentation to load locally.  I'm getting an error like this:
"XMLHttpRequest cannot load file:///E:/!MODULES/_Internal/Flash%20HTML5/Test1/images/Slide1_atlas_.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource."

It looks like there isn't a way to make this work locally?  Or is there something I'm missing?  I really have to have a solution that will allow people to load this project up on a CD.

**Comment by lannymcnie** [comment]
Local loading can not load anything using XHR due to cross-origin restrictions. I recommend a local server, such as MAMP or XAMPP.
