### ISSUE TITLE
undefined loader - preloadjs-NEXT, IE9

### ISSUE THREAD

**Issue by c-rahtz** [CreateJS/PreloadJS#170]
As described here: http://stackoverflow.com/questions/33818340/preloadjs-working-version-for-ie9-and-ie11, using the NEXT version of PreloadJS throws an undefined error in the _formatImage function.

The variable, loader, looks to be out of scope for _formatImage. If I pull the loader variable from the _formatResult function's argument, and assign it to another variable, I can access that variable from inside _formatImage, and an image will load.

This only shows up in IE9, I think, because XHR is not available, so the last else statement in that block is called.

**Comment by lannymcnie** [comment]
Will fix this ASAP. Thanks!

**Comment by wdamien** [comment]
This has been fixed in the latest release (0.6.2), you can get it here: https://code.createjs.com/preloadjs-0.6.2.min.js
