### ISSUE TITLE
preloadjs does not work with requirejs?

### ISSUE THREAD

**Issue by dudewad** [CreateJS/PreloadJS#171]
I'm following both the requirejs and preloadjs docs to the letter but can't get requirejs to obtain a reference to createjs. Here's my config:

    requirejs.config({
    	baseUrl: "script/module",
    	paths: {
    		createjs: "/bower_components/PreloadJS/lib/preloadjs-0.6.1.min"
    	},
    	shim:{
    		"createjs": {
    			"exports": "createjs"
    		}
    	}
    });

And then in my mainjs:

    define(
    	["createjs"],
    	function (createjs) {
    		//At this point all controllers are loaded and ready to go
    		console.log(createjs);
    		return {};
    	}
    );

...but creatjs when logged outputs this obect:

    {
        noConflict: ()
        parse: parse()
        runInContext: a(b,d)
        stringify: stringify()
        __proto__: Object
    }

What am I missing?  Or is this a bug? I'm on require 2.1.2 and preloadjs 0.6.1.

**Comment by dudewad** [comment]
For the record I've tried using both the 1.x and 2.x versions of exports/init functions in the shim. But the shim isn't run, meaning that preloadjs is probably already an AMD module. Just not sure how to access it via require. I'm not the only one with this issue: http://stackoverflow.com/questions/33590054/loading-preloadjs-using-requirejs

**Comment by wdamien** [comment]
Hey @dudewad , Currently PreloadJs does not properly support module loaders, like requireJS. However, support is planned for the next major release.  Keep a eye on issue #85 to be notified when support is final.

**Comment by dudewad** [comment]
Good to know, thanks for the heads up. Really enjoying the latest versions, haven't used it since a few versions back. Beautiful API!

**Comment by lannymcnie** [comment]
Thanks! We appreciate the feedback :)
