### ISSUE TITLE
Uncaught Error - anonymous define()

### ISSUE THREAD

**Issue by KK-MarcelJahn** [CreateJS/PreloadJS#180]
Hi,

your code, even in your latest version, is causing an error when using it with requirejs.
You are using an anonymous define() which is causing a Mismatch error.(http://requirejs.org/docs/errors.html#mismatch)

Precisely at https://github.com/CreateJS/PreloadJS/blob/master/lib/preloadjs-0.6.2.combined.js#L1880

Passing a String ID should solve the problem.

Thank you!

**Comment by wdamien** [comment]
Thanks for the report! Keep an eye on #85 , we will update that issue when module systems are properly supported. This specific issue is caused by JSON3, so you might want to report an issue back to them as well, https://github.com/bestiejs/json3
