### ISSUE TITLE
Add to NPM repository?

### ISSUE THREAD

**Issue by jmwohl** [CreateJS/PreloadJS#181]
Any plans to publish preloadjs to NPM? That would be super awesome.

**Comment by wdamien** [comment]
Yes, support for NPM is coming soon. Since it'll be a global createjs change, you can watch this issue https://github.com/CreateJS/EaselJS/issues/713 for updates.

**Comment by jmwohl** [comment]
:+1:

**Comment by stephanedemotte** [comment]
+1

**Comment by lannymcnie** [comment]
We have pushed npm support for the latest tagged version.

**Comment by LuisAlejandro** [comment]
Which one is the official package on npmjs.com ?
