### ISSUE TITLE
HTML5 appcache & PreloadJS supported together?

### ISSUE THREAD

**Issue by simonmacfadyen** [CreateJS/PreloadJS#186]
Apologies if this has been answered previously, the google index'd search result of this topic just redirects me to a different page (away from communities).

Essentially, i've introduced an HTML5 appcache manifest to my build. Some strange caching behaviour is happening - when I bust the cache manifest, including the reference files that I am preloading with PreloadJS:

```
// load the entry scripts
queue.loadManifest([{ 
    id: "mdnzrJS", src: 'assets/js/vendor/modernizr/modernizr-custom.min.js',
    id: "prodJS",  src: 'assets/js/dist/production.min.js'
}]);
```

The browser notifies me of the HTML5 appcache change, but my files above remain cached.

Is this a bug? or an oversight on my implementation? Is it also possible to bust the PreloadJS cache with a version bump i.e.:

```
queue.loadManifest([{ 
    id: "prodJS",  src: 'assets/js/dist/production.min.js?v=1.0.1'
}]);
```

Thanks in advance!

**Comment by fede91it** [comment]
+1

**Comment by simonmacfadyen** [comment]
Hi,

I ended up versioning the manifest with a string at the end, and it seems to work just fine. My AppCache is also bumped with every grunt/gulp build.
