### ISSUE TITLE
loadTimeout / Larger Files

### ISSUE THREAD

**Issue by whatadewitt** [CreateJS/PreloadJS#191]
Hi,

I'm preloading the main runner and css (and the images) for my application using preload.js.

When I'm on a good connection everything is fine, but when I throttle it appears that a timeout is happening even though I can see the file is still downloading.

Obviously my JS is pretty big at this point (600kb) and we're not on HTTP2 yet, so packaging everything together is my best option, but I am "initializing" my app once all files have downloaded, and because of the timeout the "complete" handler is running and there's an error because my file hasn't finished downloading.

Is there anything I can do to not have this file time out, as it appears to be the only one that is causing an issue?

Thanks,

--d

**Comment by whatadewitt** [comment]
just want to call out again that this only happens when I am throttling my connection...

**Comment by lannymcnie** [comment]
You can increase the load timeout on that item to a huge number. When loading with XHR, you may still get a timeout event from the server, but otherwise it should work:

```js
queue.loadItem({src:"bigImage.jpg", id:"image", loadTimeout:1000*60*60});
```
