### ISSUE TITLE
Not really well documented jsonp function.

### ISSUE THREAD

**Issue by belldandu** [CreateJS/PreloadJS#195]
So i'm extremely confused now.
I wanted to add jsonp to my loadqueue but from the way its documented we have to make the json return a function callback o.o?

At this point i'm more confused then i should be. So if someone could give a better explanation as to what we have to do to load json over jsonp that would be great. Because the way its documented makes no sense since you can't send javascript through json without parser errors. And the json i'm trying to call is through an api (which means it's regularly updated).

**Comment by gskinner** [comment]
Right. That is specifically how JSONP works: It wraps the JSON in a callback to avoid cross-domain restrictions. From the docs:
"A loader for JSONP files, which are JSON-formatted text files, wrapped in a callback. To load regular JSON without a callback use the JSONLoader instead.."

For more information on the difference, see the documentation for each class, or this wikipedia entry on JSONP:
https://en.wikipedia.org/wiki/JSONP
