### ISSUE TITLE
Error when loading local files on iOS

### ISSUE THREAD

**Issue by arnovanoordt** [CreateJS/PreloadJS#197]
Hello, I ran into the following:
I'm using Cordova and CreateJS to create a game for iOS and found I get an error trying to load local files (which are compiled into the ipa). When running the game as Android-app or running it as web app on an iOS device (or any other device for that matter) everything worked just fine. Trying to load files from the web also worked fine. Also using a small piece of custom code to just load a single local file worked as expected.

**Workaround**
So I figured the problem was a combination of loading local files on an iOS device using PreloadJS.
After quite a lot of digging in the preloadjs code I found the problem: there is a _checkError method that gives an error when `this._request.status` is 0, but apparently when trying to load local files on an iOS device this status is always 0 even when the files are loaded correctly. When I skip this error-check the app works just great.
For now I'll just use the code with _errorCheck in comments but it would be nice if this issue could be fixed in the next update.

PS: same goes for the SoundJS code which seems to override a lot of the PreloadJS code.

Thanks, Arno

**Comment by arnovanoordt** [comment]
Quite a lot of people have the same issue by the way: https://www.google.nl/#q=ios+local+request+status+0

**Comment by humsti** [comment]
Yay, finally! Had the same issue here with some of our html5 games (using PreloadJS) as we tried to convert them into native apps. Thanks for sharing your solution - I wasted hours on this without luck :)

**Comment by lannymcnie** [comment]
The status check was addressed in March, and is part of the NEXT version of PreloadJS. 

Note that SoundJS compiles in PreloadJS classes. The classes are updated, but a NEXT version has not been made yet. We can generate a NEXT version shortly.

**Comment by lannymcnie** [comment]
Pushed latest.

**Comment by lannymcnie** [comment]
Note: This fix causes CORS errors to not be properly caught. 

I have reverted this change somewhat, and only surfaced the error when on "http:" or "https:" protocol. Should still let `status:0` through on Cordova or other compiled apps. Will prevent CORS errors from being surfaced when locally testing on file:, but that is not a great practice anyways.
