### ISSUE TITLE
Need to preload SWF

### ISSUE THREAD

**Issue by kirkstrobeck** [CreateJS/PreloadJS#198]
``` js
that.preloadQueue.loadManifest([
  { id: 'ball', src: '/swf/ball.swf' },
]);
```

Then I use swfobject and just use the normal filepath at `'/swf/ball.swf'`. How should I change it?

**Comment by kirkstrobeck** [comment]
Also http://stackoverflow.com/questions/37283559/swf-preloading-with-preloadjs

**Comment by lannymcnie** [comment]
Posted to [StackOverflow](http://stackoverflow.com/questions/37283559/swf-preloading-with-preloadjs/37285279#37285279):

> There is no SWF-based preloading available for PreloadJS. If the file extension is not recognized, the file will be loaded as plain text via XHR, and will therefore not be stored in the browser cache. When the Embed/Object is created in HTML, it will need to load it again from scratch, so the preload is just overhead.

> In order to support SWF loading, a "SWFLoader" plugin would have to be created which properly loads the SWF using SWFObject or something similar. Due to the lack of Flash on the web these days, I don't think official support will ever be added to PreloadJS, unless there is overwhelming requests for it.

**Comment by lannymcnie** [comment]
We have no plans to build a SWF loader -- so I am closing this out.
