### ISSUE TITLE
A way to force XHR2 on all loaders, to enable individual fileprogress events?

### ISSUE THREAD

**Issue by supermoos** [CreateJS/PreloadJS#206]
Is there a way to force XHR2 on all loaders, to enable individual fileprogress events?

It would be nice if you're loading big assets (say a 10 mb image), to be able to get progress events while the file is downloading (0%...2%...3%.. etc.), instead of just a completed event.

Should be possible with XHR2, but a lot of the loaders seem to default to just XHR, with no way to force XHR2.

But maybe I'm overlooking something?

**Comment by lannymcnie** [comment]
PreloadJS supports `progress` events from loaders, as well as `fileprogress` events from LoadQueue. This proxies XHR2 progress events. As long as you are using XHR-based loaders, and the server supports it, you will get XHR2 progress events.

For an example, check out the [Preload Queue](http://www.createjs.com/demos/preloadjs/preloadqueue) sample on CreateJS.com. If you either "load all", or click "load another" quickly to queue up a few, it is quite evident. The demo has a progress bar for the overall queue, as well as progress bars for each asset, and you can see they don't just go from 0-100%

Cheers,

**Comment by supermoos** [comment]
Thanks @lannymcnie for clearing up the server support. My bad :-)
