### ISSUE TITLE
Loading on IE9

### ISSUE THREAD

**Issue by gjbarter** [CreateJS/PreloadJS#208]
Hi,

I'm having an issue with loading assets through PreloadJS on IE9. I'm getting the following error:

`SCRIPT5: Access is denied.`

The assets i'm loading are coming from another server so I'm thinking it's probably something to do with cross-domain permissions but can't seem to see anything referencing a fix for this.

I've tried to use the NEXT version but no luck.

Anyone able to help?

Thanks in advance!

**Comment by lannymcnie** [comment]
What sort of assets are you loading? If they are images, you might need to ensure they are CORS-safe. This involves delivering assets with an allow-access header, and passing `crossOrigin=true` to the asset or LoadQueue.

**Comment by lannymcnie** [comment]
Closing for now. If more details can be posted, we can reopen this one.
