### ISSUE TITLE
Loading videos

### ISSUE THREAD

**Issue by kevingobert** [CreateJS/PreloadJS#209]
I use PreloadJS to preload a lot of video.

Here's the setup: [http://pastebin.com/9P6HywQA](http://pastebin.com/9P6HywQA)

Preloading works, I have many XHR requests.

The problem is when I use its videos (I add in javascript) the browser reload the new media completely and doesn't use the cache.

Preload : [https://www.dropbox.com/s/3sqh7vkyize1tbq/Capture%20d%27%C3%A9cran%202016-08-12%2010.52.35.png?dl=0](https://www.dropbox.com/s/3sqh7vkyize1tbq/Capture%20d%27%C3%A9cran%202016-08-12%2010.52.35.png?dl=0)

When I use the media :
[https://www.dropbox.com/s/xi5fsa8n1skani2/Capture%20d%27%C3%A9cran%202016-08-12%2010.55.40.png?dl=0](https://www.dropbox.com/s/xi5fsa8n1skani2/Capture%20d%27%C3%A9cran%202016-08-12%2010.55.40.png?dl=0)

**Comment by kevingobert** [comment]
Nobody sees the problem ?
Thank you

**Comment by lannymcnie** [comment]
Have you tried loading with `preferXHR=false`? XHR-loaded assets will not pull from the cache, and instead use blob-URLs, but it sounds like videos don't work this way.
