### ISSUE TITLE
maintainCSSOrder Support

### ISSUE THREAD

**Issue by djangosdk** [CreateJS/PreloadJS#211]
Hi,
I am using this plugin load all my index dependencies.
I find ````maintainScriptOrder``` very helpful but I also need to ```maintainCSSOrder``` as I have lots of css files and one step down css file sometimes overwrites above css file.
For example:
1- some-plugin.css
2- some-plugin-override.css

Should I be worried or if I define css in correct order in manifest.json then In html header css will appear in same order even though some smaller sized css might be loaded before the other large sized css?

**Comment by lannymcnie** [comment]
You can define `maintainOrder` on any item in the queue, and it will load in the order that the items are defined.

var queue = new createjs.LoadQueue();
queue.loadManifest([
    {src:"item1.css", maintainOrder:true},
    {src:"item2.css", maintainOrder:true},
    {src:"item3.jpg"},
    {src:"item4.css", maintainOrder:true},
    {src:"item5.jpg"},
]);

In this example, item 1, 2, and 4 will always finish in the expected order. Items 3 and 5 might get queued up at the same time as another loading item, and could finish earlier or in a different order, but only if `maxConnections` is greater than 1.

Cheers.
