### ISSUE TITLE
[Bug?]Undefined variable

### ISSUE THREAD

**Issue by hiroqn** [CreateJS/PreloadJS#213]
_this is undefined but src directory is fixed

https://github.com/CreateJS/PreloadJS/blob/master/lib/preloadjs-0.6.2.combined.js#L6352

https://github.com/CreateJS/PreloadJS/blob/master/src/preloadjs/loaders/ImageLoader.js#L164

**Comment by hiroqn** [comment]
#170 
#188

**Comment by lannymcnie** [comment]
We have not yet tagged PreloadJS, but the NEXT version has been fixed since Dec 21, 2015. Closing this.
