### ISSUE TITLE
on/removeEventListener or on/off doesn't work

### ISSUE THREAD

**Issue by keitakun** [CreateJS/PreloadJS#217]
Using the EventDispatcher's .on() method and later using .removeEventListener() or .off() doesn't remove the event listener.

Example: https://jsfiddle.net/kd36k3hv/

**Comment by gskinner** [comment]
You need to unsubscribe the proxy object that is created by `on()`.

Please see the EventDispatcher.on() docs for more info and an example:
http://createjs.com/docs/easeljs/classes/EventDispatcher.html#method_on
