### ISSUE TITLE
ImageLoader._isLocal() method does not exist

### ISSUE THREAD

**Issue by FumioNonaka** [CreateJS/PreloadJS#236]
https://github.com/CreateJS/PreloadJS/blob/6c3514bc53248131485c2526f085928ebabb2ca8/VERSIONS.txt#L18
Isn't it URLUtils.isLocal(() call in ImageLoader.load() method?
https://github.com/CreateJS/PreloadJS/commit/a47de23fc4cb6887b5fe3819f4c04c2b4adece91#diff-ff6e0fb16e84ed3ea64ebada0d4e3bf2

**Comment by lannymcnie** [comment]
Yes, I think it got changed after initially fixing it. Closing this report, as the VERSIONS change was accurate when it was created.
