### ISSUE TITLE
Cannot find module 'preloadjs.js'

### ISSUE THREAD

**Issue by brunoimbrizi** [CreateJS/PreloadJS#238]
In package.json, shouldn't `"main": "preloadjs.js",` be pointing to `"main": "lib/preloadjs.js",`?

As is, trying to `import 'preloadjs';` results in an error `Cannot find module 'preloadjs.js'`.
Modifying the `"main"` attribute manually makes it work fine.

**Comment by lannymcnie** [comment]
You might be right. The CreateJS libraries don't currently have any exports, so you can't use them with Require/Common module loaders (yet, next version!!). I will look at addressing that issue in the mean time. Thanks!

**Comment by 3dos** [comment]
Manually modifying the package.json like mentioned didn't do the trick for me. I can't wait to see the next version with module exports coming ! In the meantime, I'm using this little package : https://www.npmjs.com/package/preload-js

**Comment by lannymcnie** [comment]
Closing for now. We will ensure that the next version has full import support.

**Comment by combs** [comment]
I'm still seeing `"main": "preloadjs.js"` in the package.json for npm `preloadjs` 1.0.1 FWIW
