### ISSUE TITLE
AbstractLoader error handling problem

### ISSUE THREAD

**Issue by tjutasi** [CreateJS/PreloadJS#243]
When I have a response 403 and something xml in response data for a request (which seems a common response at Amazon S3/CloudFront instead of 404) AbstractLoader handle it as a completed request, instead of an error.
Error handling should be based on request status.

**Comment by lannymcnie** [comment]
What version are you using? All server status codes between 400 and 599 are treated as errors. This was changed a while back (March, 2016), so if you are using 0.6.2, then you would see 403 not treated as an error. 

* [Error handler in latest version](https://github.com/CreateJS/PreloadJS/blob/master/src/preloadjs/net/XHRRequest.js#L397)
* [Commit where this changed](https://github.com/CreateJS/PreloadJS/commit/ca64cc67d7e6241d73474e41328cd3d1ed81b48d)
