### ISSUE TITLE
Files are not loading from manifest when type attribute is present

### ISSUE THREAD

**Issue by downtroden** [CreateJS/PreloadJS#258]
Version: 1.0.0
OS & Browser: Mac 10.13.6 / Chrome 72.0.3626.109
### Issue Details

When I include the type attribute in the JSON manifest, files do not load. If type is removed files load, but with wrong MIME type. Docs lead me to believe that 'type' is a valid attribute to include in the JSON.

**Sample Manifest JSON** Broken
`
{
	"path":"https://images.unsplash.com/",
	"manifest": [
		{
			"id":"stair_boy",
			"src":"photo-1542838454-d4dce2a7cfde?fit=crop&h=500&q=60",
			"type":"createjs.Types.IMAGE"
		},
		{
			"id":"night_bridge",
			"src":"photo-1549948558-1c6406684186?fit=crop&h=500&q=60",
			"type":"createjs.Types.IMAGE"
		}
]}
`

**Comment by lannymcnie** [comment]
Your types are using the constants as strings. You can use either "image" or `createjs.Types.IMAGE` (which evaluates to "image"). But not "createjs.Types.IMAGE". 

If you are using an external manifest, use the string "image".

Cheers!
