### ISSUE TITLE
Redirected (302) Images does not work on Safari

### ISSUE THREAD

**Issue by josimard** [CreateJS/PreloadJS#28]
Hi, 
redirected images does not seem to work yet with safari.

Sometimes it's the only way some image can be obtained, such as facebook profiles images:
http://graph.facebook.com/USER_ID/picture?type=large

Cheers

- Jonathan

**Comment by wdamien** [comment]
This will work if you use tag loading.  ```var  q = new createjs.LoadQueue(false);```.
XHR is throwing errors when loading in Safari, so leaving a "BrowserBug" for that issue.
