### ISSUE TITLE
Preloading many audio files crashes Chrome/Safari

### ISSUE THREAD

**Issue by onedrop** [CreateJS/PreloadJS#29]
I'm using preload js to load in a lot of  audio files and webkit browsers are crashing.

View source on this for a simple demonstration...
http://habel.net/game/webkit_crash.html

I think it may in fact be a bug with the browsers because if you do document.createElement('audio') a bunch of times and cache the elements in an array, the crash will also occur. Was hoping there would be some type of workaround you could suggest.

**Comment by lannymcnie** [comment]
Closing this out. Feel free to reopen if the issue persists.
