### ISSUE TITLE
Preloading video files sort of works but breaks the queue

### ISSUE THREAD

**Issue by Ultroman** [CreateJS/PreloadJS#39]
I'm creating a system in which a bunch of images tween across the background with different effects. I can load as many images as I want, and they all tween nicely. Now I've even made it work with videos, so it pauses until the video ends, and then it moves on to the next image or video.

The problem I'm experiencing, is that when I create a manifest of URLs to the images and then add in a video at ANY point in the manifest (first, last, middle, anything), it removes an element from the end of the manifest per mp4 file in the manifest.

As I said, the video works perfectly once it's loaded, though.

If I load in this order, image4 disappears while running loadManifest(manifest), but the other elements work:
image1.jpg
image2.jpg
video1.mp4
image3.jpg
image4.jpg

If I load in this order, video1 disappears, but the other elements work:
image1.jpg
image2.jpg
image3.jpg
image4.jpg
video1.mp4

If I load only the video, it says that no elements were loaded, and if I load the video first and then an image, only the image is loaded.

So your video-preloading works just fine, except your loading-script does not seem to accept it. Probably because it isn't one of the 'types', but you know better than I.

**Comment by wdamien** [comment]
Support for preloading video was added in v0.6.0, please re-open if this is still an issue.
