### ISSUE TITLE
getResult IE8 fail

### ISSUE THREAD

**Issue by sidneivl** [CreateJS/PreloadJS#57]
Hi,

I'm getting an strange error in IE8, when I load my page I start a queue loading and after finish I get a result by Id.

But sometime I can get correct value and some times not.

For example I'm loading an image:

queue = new createjs.LoadQueue()
mainfest = []
mainfest.push({id:"imagebackground", src:data['pathBackground']})
queue.onComplete 	= handleComplete
queue.loadManifest(mainfest)

function handleComplete(e){
 queue.getResult('imagebackground')
}

sometimes this code return me a correct image, otherwise return me a document object.

Anyone know about this issue and can help me?

Thanks

**Comment by lannymcnie** [comment]
IE8 is no longer supported by PreloadJS. Please continue to use version 0.4.1 if you need IE8 compatibility.
