### ISSUE TITLE
Question: Vimeo and Youtube

### ISSUE THREAD

**Issue by howardroark** [CreateJS/PreloadJS#58]
Hi,

Would there be any interest in adding hooks which let you you also track the readiness of Vimeo iframes?  They tend to disrupt the parent document as they load their respective DOMs, making sites that need a lot resources jumpy before that occurs.

With the use of html5 postmessage it should be quite doable.

If there was a willingness to require libraries such as froogaloop or the youtube api library, you could ensure a method to stay in sync with the vendor's changes.

I will probably do this on my own, but I was just wondering if it would be worth while to study your code style and try to make it an official pull request.

Thanks!

**Comment by lannymcnie** [comment]
I am closing this. Definitely open to a pull request with a plugin.
