### ISSUE TITLE
IE7: Preloading only functions on first load of the page

### ISSUE THREAD

**Issue by benwick** [CreateJS/PreloadJS#59]
Test it with this html-page and some picture you call a "an-image.jpg":

```
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>
    <body>
        <script src="js/preloadjs-NEXT.min.js"></script>
        <script>
            var test = new createjs.LoadQueue();
            test.loadFile('an-image.jpg');
            test.addEventListener('fileload', function() {
                alert('load');
            });
            test.addEventListener('complete', function() { 
                alert('complete');
            });
        </script>
    </body>
</html>
```

When you open that page the first time in IE7, the alerts in the fileload and complete listeners will fire. When you refreh the page, the events won't fire anymore. Will you open a new tab and load the page, everything works fine - until the reload in the same tab...

**Comment by wdamien** [comment]
Closing, since IE7 is pretty much a dead browser now. http://www.theie7countdown.com/
