### ISSUE TITLE
<XML> result.firstChild.children

### ISSUE THREAD

**Issue by FabianPP** [CreateJS/PreloadJS#63]
I took the PreloadJS-release_v0.4.0/examples/MediaGrid.html
and added one line to log the children of the XML.
....
case createjs.LoadQueue.XML:
alert(result);
div.innerHTML = "<label>Complete :)</label>";
console.log(result.firstChild.children);
break;
....

FF and Chrome give me a [object HTMLCollection]
but IE 10 says "undefined"

**Comment by wdamien** [comment]
IE's XML parser is slightly different from other browses, use ```result.documentElement.firstChild```
