### ISSUE TITLE
XDomainRequest failing on second request in IE9 and 10

### ISSUE THREAD

**Issue by aaronjbaptiste** [CreateJS/PreloadJS#69]
I'm downloading pngs from another domain, using something like the following code:

```javascript
var loader = new createjs.LoadQueue(true, 
  "http://mydomain.com/images/", 
  "http://mydomain.com");
var that = this;

loader.addEventListener("fileload", function(e) { 
  var bitmap = new createjs.Bitmap(e.result);
  that.el.addChild(bitmap);
  that.el.addEventListener("click", function() { alert("works") });
});

loader.loadFile(this.model.get("url"));
```

They display fine but mouse events are throwing:

```
An error has occurred. This is most likely due to security restrictions on reading canvas pixel data with local or cross-domain images
```

The server is set up for CORS, Response Header:

```
Key	Value
Response	HTTP/1.1 200 OK
Date	Tue, 17 Dec 2013 12:29:36 GMT
Server	Apache/2.2.15 (CentOS)
Accept-Ranges	bytes
Content-Length	65722
Cache-Control	public
Expires	Thu, 15 Apr 2020 20:00:00 GMT
Access-Control-Allow-Origin	*
Connection	close
Content-Type	image/png
```

Chrome and IE11 are fine, the mouse event is being thrown correctly.

Oddly, in IE9/10, there are two requests made for the image, the first has the Origin header set, the second doesn't. In Chrome, both requests have the Origin header set.

So, 1) I don't understand why there are two request being made in the first place. Is XHR failing and it's falling back to tag based?

2) Shouldn't IE9/10 have the Origin header set on the second request?

I'm using preloaderjs 0.4.1

Also note, forcing tag based loading by: new createjs.LoadQueue(false,....) does not fix the problem.

**Comment by wdamien** [comment]
In v0.6.0 XHR image loading was changed to use blob:// urls, so IE10+ will now work with CORS images. Closing since the IE 9 issue is an FOL (unless you use tag loading, or the above mentioned base64 hack).
