### ISSUE TITLE
Loading JS automatically get's injected to the DOM

### ISSUE THREAD

**Issue by davidpaulrosser** [CreateJS/PreloadJS#72]
Is there anyway to stop this happening?

The app I'm currently building requires the first manifest to finish loading before executing the app. PreloadJS seems to inject the script after loading.

Thanks,

David.

[Edit]

I've just noticed that you added this feature in 0.4.1
http://www.createjs.com/Docs/PreloadJS/classes/LoadQueue.html#property_JAVASCRIPT

To avoid this i'm going to revert to 0.4.0 for now.

**Comment by stephanedemotte** [comment]
+1 we need to load js, not insert it :)

Same things for css, when loaded, it be inserted into the dom...

Thanks !
