### ISSUE TITLE
Browserify compatibility (UMD/AMD/CommonJS)

### ISSUE THREAD

**Issue by fregante** [CreateJS/PreloadJS#85]
I just started using Browserify and noticed that PreloadJS v0.4.1 was causing the error `createjs is not defined` in the browser. 

While it would be great to have proper CommonJS syntax, simply replacing all the `this.createjs` with `window.createjs` fixed the issue. This makes sure a global variable is created, rather than using `this` in the [closure Browserify generates](http://benclinkinbeard.com/posts/how-browserify-works/).

Is there any reason to use `this` instead of simply `window`? Can you apply this fix to the source?

**Comment by vanillabass** [comment]
+1

**Comment by tommoor** [comment]
+1

**Comment by jamjar121212** [comment]
+1

**Comment by killroy42** [comment]
+1 Once again stalled with cryptic "Cannot find module" errors from soundjs. So many wasted hours :(

**Comment by not-only-code** [comment]
+1

**Comment by vash15** [comment]
+1

**Comment by SyntaxStacks** [comment]
+1

**Comment by mkay581** [comment]
+1

**Comment by caranicas** [comment]
+1

**Comment by SyntaxStacks** [comment]
so assuming it is as easy as changing ```this.createjs``` with ```window.createjs``` where's the PR?

**Comment by lannymcnie** [comment]
@SyntaxStacks Feel free to submit a pull request. This is a fairly pervasive change, even if it is simple, and has to be made across all libraries at once.

**Comment by SyntaxStacks** [comment]
I'm adding the following to solve this issue:
```
if (typeof window === 'undefined') {
    this.createjs = this.createjs || {};
} else {
  window.createjs = window.createjs || {};
}
```

any recommendations?

**Comment by lannymcnie** [comment]
One of our developers started working on an implementation in the browserify_support branch. https://github.com/CreateJS/PreloadJS/tree/browserify_support

**Comment by ryanfields** [comment]
Just as a warning, @SyntaxStacks suggestion could break Webpack builds.  In general, forcefully pushing createjs into the window object doesn't play nice with browser-targeting CommonJS build tools.

**Comment by SyntaxStacks** [comment]
@ryanfields thanks for the heads up.

**Comment by szmeku** [comment]
+1

**Comment by gugiserman** [comment]
+1 !

**Comment by kenshiroh** [comment]
+1

**Comment by lannymcnie** [comment]
Thanks for all the +1's. This is on our roadmap for the next major release.

**Comment by dnlsandiego** [comment]
+1

**Comment by crowd-studio** [comment]
+1

**Comment by WWWillems** [comment]
+1

**Comment by jdbence** [comment]
I don't know the repercussions of not using **this** or **window** but I've used CreateJS in Webpack.

Step 1 : In the minified createjs file, replace all references of **this.createjs** and **window.createjs** with **createjs**

Step 2: Tell Webpack to make **createjs** a global. You'll need to change the path to your file location.

```javascript
plugins: [
  new webpack.ProvidePlugin({
    'createjs': 'imports?this=>global!exports?createjs!createjs',
  })
],
resolve: {
  root: paths.base('src'),
  extensions: ['', '.js', '.jsx'],
  alias: {
    'createjs' : path.join(__dirname, '../../vendor/createjs-2015.11.26.min.js'),
  }
}
```

**Comment by liveme** [comment]
+1

**Comment by Dijir** [comment]
+1

**Comment by WoLfulus** [comment]
+1

**Comment by lannymcnie** [comment]
We get it! Everyone +1's this!

We are working on support for a upcoming/future release, and it is a high priority. We appreciate all your feedback and requests, and will do what we can to support these frameworks.

No need to add additional +1s :D

**Comment by lannymcnie** [comment]
Now that 1.0 has been released, we are making this a top priority as we shift to ES6.
