### ISSUE TITLE
Can not pass an SVG instance to Bitmap

### ISSUE THREAD

**Issue by margagn** [CreateJS/PreloadJS#91]
I am unable to preload a SVG object and pass it to Bitmap. Is this by design?

For more details, please see the following question: http://stackoverflow.com/questions/25608721/unable-to-preload-and-display-svg-with-createjs

**Comment by wdamien** [comment]
Closing, since this is an EaselJS issue. For more details on SVG support check: https://github.com/CreateJS/EaselJS/issues/456
